## **Task 1 - Broadcasted Distance Calculation**

- Objective: Compute pairwise Euclidean distances between two sets of points **without loops**.


Here's the Euclidean distance formula in Markdown format:

### Euclidean Distance Formula

The Euclidean distance between two points $$p = (p_1, \ldots, p_n)$$ and $$q = (q_1, \ldots, q_n)$$ in n-dimensional Euclidean space is defined as:

$$
d(p,q) = \sqrt{\sum_{i=1}^{n} (q_i - p_i)^2}
$$

#### For 2D Space (x-y plane)

In two-dimensional space, for points $$p = (x_1, y_1)$$ and $$q = (x_2, y_2)$$, the formula simplifies to:

$$
d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$

This formula calculates the straight-line distance between two points by taking the square root of the sum of squared differences of their coordinates.

**Task Details:**

Inputs:

- X: a 2D array of shape (N, D) for N points in D-dimensional space.
- Y: a 2D array of shape (M, D) for M points in D-dimensional space.

Output:
- dist: a 2D array of shape (N, M), where dist[i, j] is the Euclidean distance between X[i] and Y[j].

Hint: Use broadcasting

### **Example**

```python
import numpy as np

X = np.array([[0, 0],
              [1, 1],
              [2, 2]])  # Shape (3, 2)

Y = np.array([[0, 0],
              [0, 1],
              [1, 1],
              [2, 2]])  # Shape (4, 2)

# Expected dist array:
# Distances between:
# When X[0]=(0,0) and Y: (0,0) distance will be 0,  and when Y: (0,1) distance will be 1, and when Y: (1,1) distance will be √2≈1.4142, and when Y: (2,2) distancw will be √8≈2.8284, so the first row in distance matrix will be [0.        , 1.        , 1.41421356, 2.82842712]

# X[1]=(1,1), Y: (0,0)=√2, (0,1)=1,      (1,1)=0,        (2,2)=√2≈1.4142
# X[2]=(2,2), Y: (0,0)=√8, (0,1)=√5≈2.2361, (1,1)=√2≈1.4142, (2,2)=0

# dist should be approximately:
# [[0.        , 1.        , 1.41421356, 2.82842712],
#  [1.41421356, 1.        , 0.        , 1.41421356],
#  [2.82842712, 2.23606798, 1.41421356, 0.        ]]
```

In [3]:
import numpy as np

def compute_pairwise_distances(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    """
    Compute the pairwise Euclidean distances between two sets of points.

    Args:
    - X (np.ndarray): A 2D array of shape (N, D) for N points in D-dimensional space.
    - Y (np.ndarray): A 2D array of shape (M, D) for M points in D-dimensional space.

    Returns:
    - np.ndarray: A 2D array of shape (N, M), where dist[i, j] is the Euclidean distance between X[i] and Y[j].
    """
    # Broadcasting difference calculation and summing up squares of differences
    dist = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :]) ** 2, axis=2))
    return dist

# Example
X = np.array([[0, 0],
              [1, 1],
              [2, 2]])  # Shape (3, 2)

Y = np.array([[0, 0],
              [0, 1],
              [1, 1],
              [2, 2]])  # Shape (4, 2)

dist = compute_pairwise_distances(X, Y)
print(dist)

[[0.         1.         1.41421356 2.82842712]
 [1.41421356 1.         0.         1.41421356]
 [2.82842712 2.23606798 1.41421356 0.        ]]


## **Task 2- Row-wise and Column-wise Normalization**

- Objective: Normalize rows and columns of a matrix so that each row or column sums to 1.

**Task Details:**

Input:

- A: a 2D array (N, M).

Outputs:
- A_row_norm: same shape as A, each row sums to 1.
- A_col_norm: same shape as A, each column sums to 1.
Hint:

Row normalization: A_row_norm = A / A.sum(**put your params here**)
Column normalization: A_col_norm = A / A.sum(**put your params here**)

```python
A = np.array([[1, 2],
              [3, 4]])

# Row sums: [3, 7]
# A_row_norm:
# [[1/3, 2/3],
#  [3/7, 4/7]]
# ≈ [[0.33333333, 0.66666667],
#    [0.42857143, 0.57142857]]

# Column sums: [4, 6]
# A_col_norm:
# [[1/4, 2/6],
#  [3/4, 4/6]]
# = [[0.25, 0.33333333],
#    [0.75, 0.66666667]]
```

In [5]:
import numpy as np

def normalize_matrix(A: np.ndarray) -> (np.ndarray, np.ndarray):
    # Row-wise normalization (normalize each row so that it sums to 1)
    A_row_norm = A / A.sum(axis=1, keepdims=True)
    
    # Column-wise normalization (normalize each column so that it sums to 1)
    A_col_norm = A / A.sum(axis=0, keepdims=True)
    
    return A_row_norm, A_col_norm

# Example usage
A = np.array([[1, 2],
              [3, 4]])

A_row_norm, A_col_norm = normalize_matrix(A)

# Printing row-wise normalization
print("Row-wise Normalized Matrix (A_row_norm):")
print(A_row_norm)

# Printing column-wise normalization
print("\nColumn-wise Normalized Matrix (A_col_norm):")
print(A_col_norm)


Row-wise Normalized Matrix (A_row_norm):
[[0.33333333 0.66666667]
 [0.42857143 0.57142857]]

Column-wise Normalized Matrix (A_col_norm):
[[0.25       0.33333333]
 [0.75       0.66666667]]


## **Task 3- Elementwise Condition Replacement**

- Objective: Replace elements based on conditions without loops.

**Task Details:**

Input:

- x: a 1D array.
- T: a threshold.

**Steps:**

- Replace all negative values in x with 0.
- Replace all values greater than T with the mean of values at below T.

```python
x = np.array([-2, -1, 0, 5, 10])
T = 5

# Step 1: Replace negatives with 0: x -> [0,0,0,5,10]
# Values ≤ T are [0,0,0,5], mean = (0+0+0+5)/4 = 1.25
# then values at or below T=5 are [0,0,0,5], mean=1.25, final x=[0,0,0,5,1.25].
```

In [6]:
import numpy as np

def replace_elements(x: np.ndarray, T: float) -> np.ndarray:
    # Step 1: Replace all negative values with 0
    x = np.where(x < 0, 0, x)
    
    # Step 2: Find the mean of values ≤ T
    values_below_T = x[x <= T]
    mean_below_T = values_below_T.mean() if len(values_below_T) > 0 else 0
    
    # Step 3: Replace all values greater than T with the mean of values ≤ T
    x = np.where(x > T, mean_below_T, x)
    
    return x

# Example usage
x = np.array([-2, -1, 0, 5, 10])
T = 5

result = replace_elements(x, T)
print(result)


[0.   0.   0.   5.   1.25]


## **Task 4- 2D Linear Transformations**

- Objective: Apply a linear transformation to a set of 2D points using matrix multiplication.

Task Details:

Inputs:

- points: (N, 2) array of points.
- T: (2, 2) transformation matrix.

```python

points = np.array([[1, 0],
                   [0, 1],
                   [1, 1]])

# A 90-degree rotation matrix is:
T = np.array([[0, -1],
              [1,  0]])

# points_transformed:
# [[ 0, -1],
#  [ 1,  0],
#  [ 1, -1]]
```

In [7]:
import numpy as np

def apply_transformation(points: np.ndarray, T: np.ndarray) -> np.ndarray:
    # Apply the linear transformation using matrix multiplication
    return points @ T

# Example usage
points = np.array([[1, 0],
                   [0, 1],
                   [1, 1]])

T = np.array([[0, -1],
              [1,  0]])

points_transformed = apply_transformation(points, T)
print(points_transformed)

[[ 0 -1]
 [ 1  0]
 [ 1 -1]]
